site_name: 'VisualKey'
site_description: 'Computer graphics sketchbook.'
site_author: 'Leonardo Mariscal'
site_url: 'https://visualkey.org'
edit_uri: 'https://github.com/lmariscal/visualkey-docs/edit/master/docs'
copyright: 'Copyright &copy; 2020 SAE Institute México'
repo_name: 'lmariscal/visualkey'
repo_url: 'https://github.com/lmariscal/visualkey'
theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  plugins:
    - search
    - minify:
        minify_html: true
extra:
  social:
    - type: 'github'
      link: 'https://github.com/lmariscal'
    - type: 'twitter'
      link: 'https://twitter.com/lmariscal_'
markdown_extensions:
  - codehilite
  - admonition
nav:
  - 'Getting Started': 'index.md'
  - 'Window': 'window.md'
  - 'Graphics': 'graphics.md'
  - 'Math': 'math.md'