site_name: 'VisualKey'
site_description: 'Computer graphics sketchbook.'
site_author: 'Leonardo Mariscal'
site_url: 'https://visualkey.org'
edit_uri: 'https://github.com/lmariscal/visualkey-docs/edit/master/docs'
copyright: 'Copyright &copy; 2020–<script>document.write(new Date().getFullYear())</script> SAE Institute México'
repo_name: 'lmariscal/visualkey'
repo_url: 'https://github.com/lmariscal/visualkey'
theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  plugins:
    - search
    - minify:
        minify_html: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/lmariscal'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/lmariscal_'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
nav:
  - 'Getting Started': 'index.md'
  - 'Audio': 'audio.md'
  - 'Graphics': 'graphics.md'
  - 'Input': 'input.md'
  - 'Math': 'math.md'
  - 'Shader': 'shader.md'
  - 'Time': 'time.md'
  - 'Texture': 'texture.md'
  - 'Window': 'window.md'
  - 'Camera': 'camera.md'
  - 'Light': 'light.md'
  - 'Text': 'text.md'
